### ISSUE TITLE
Please add a right-left option

### ISSUE THREAD

**Issue by danielbrunt57** [custom-cards/slider-button-card#22]
**Is your feature request related to a problem? Please describe.**
My vertical slat binds open from right to left.  I am currently using left-right (the **_only_** option) and also invert: true and this gives me the correct visual representation of the blind opening from right to left.  The problem then becomes the percentage open is reversed 70% open shows as 30% in the card.

**Describe the solution you'd like**
I think there needs to be two invert options - one for the blind visual and another for the entity values, if necessary.  In HA my entity shows closed at 100%.  In your card with invert: true, it shows closed at 0% and every percentage in between is reversed.

**Describe alternatives you've considered**
I have played with the settings to no avail and I've searched for other custom cards also to no avail.

**Additional context**
![image](https://user-images.githubusercontent.com/49846893/178624773-c42a38ab-0e07-4827-a56d-9ba2ee092bac.png)
![image](https://user-images.githubusercontent.com/49846893/178624802-c4403d42-ca30-4d02-8721-027eb06670de.png)
![image](https://user-images.githubusercontent.com/49846893/178625274-bf294f89-7555-435b-a59c-0682c031c097.png)

**Comment by rohankapoorcom** [comment]
#53 should fix this

**Comment by danielbrunt57** [comment]
Thanks, that's much better!  Not perfect yet but you'd likely want it as a new FR.
```
  - type: custom:slider-button-card
    slider:
      direction: right-left
      background: solid
      use_state_color: false
      use_percentage_bg_opacity: true
      toggle_on_click: false
      show_track: true
      force_square: false
      invert: false
    action_button:
      mode: toggle
      show: false
    icon:
      icon: ''
      show: false
      use_state_color: false
    entity: cover.south_patio_door
    show_state: true
    compact: false
    name: Patio Door
    show_name: false
```
![image](https://github.com/custom-cards/slider-button-card/assets/49846893/106269a0-00bf-47e3-898e-8654261fd33c)

![image](https://github.com/custom-cards/slider-button-card/assets/49846893/4e4e036c-90e8-4118-a918-7fb57bddc95d)

![image](https://github.com/custom-cards/slider-button-card/assets/49846893/ff6f5027-832b-4bf7-8578-8951886645c3)

At lease Open-Percentage Open-Closed matches the state of the device.  It would be nice not have a black foreground for the curtain.  A `forground: striped option` would be nice!!

**Comment by rohankapoorcom** [comment]
I don't use the solid background option myself. I recommend the gradient one instead. See the photo attached to https://github.com/custom-cards/slider-button-card/issues/48#issuecomment-1676088480

```
type: custom:slider-button-card
entity: light.office_lights
slider:
  direction: right-left
  background: gradient
  use_state_color: true
  use_percentage_bg_opacity: false
  show_track: false
  toggle_on_click: false
  force_square: false
show_name: true
show_state: true
name: Right to Left
```
