### ISSUE TITLE
Slider option - minimum value (Lights)

### ISSUE THREAD

**Issue by Nornode** [custom-cards/slider-button-card#37]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when sliding a dimmer to the lowest value, it turns my lights off, not to 1% light.

Using the toggle to turn it off completely

**Describe the solution you'd like**
on slider: definition implements a `min:` (And a `max:`) configuration.

e.g.:

```
    slider:
      direction: left-right
      background: gradient
      use_state_color: true
      use_percentage_bg_opacity: false
      force_square: false
      min: 1
```
Last line! ☝️

**Describe alternatives you've considered**
Use another less nice card.
