### ISSUE TITLE
Change icon color

### ISSUE THREAD

**Issue by sanderhoeppermans** [custom-cards/slider-button-card#65]
Is there a way to change the color or the icon? Haven't found it yet. 

I was trying to make it red (see code), unfortunately without any result. 

<img width="982" alt="image" src="https://github.com/custom-cards/slider-button-card/assets/121697071/5261a275-264e-4ef1-9fa0-d94e82e87908">

**Code**:
```
type: custom:slider-button-card
entity: cover.ramen
slider:
  direction: left-right
  background: gradient
  use_state_color: true
  use_percentage_bg_opacity: false
  show_track: true
  toggle_on_click: false
  force_square: false
show_name: true
show_state: true
compact: true
icon:
  show: true
  use_state_color: true
  tap_action:
    action: more-info
  icon: mdi:curtains
  styles:
    icon:
      - color: '#FF0000'  # Red color code
action_button:
  mode: custom
  icon: mdi:curtains
  show: false
  show_spinner: true
  tap_action:
    action: toggle
name: Gordijnen

```
