### ISSUE TITLE
SWITCH: Action button not working for Call service

### ISSUE THREAD

**Issue by KirkKirk** [custom-cards/slider-button-card#77]
**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:** v1.13.0

**Last working release (if known):** n/a

**Browser and Operating System:** hass / chrome / win10

**Description of problem:** Failed to call service switch/toggle. must contain at least one of entity_id, device_id, area_id, floor_id, label_id.

**Javascript errors shown in the web inspector (if applicable):**

```
type: custom:slider-button-card
entity: number.boiler_controler_set_power
show_state: true
slider:
  direction: left-right
  background: gradient
  use_state_color: true
  compact: true
  toggle_on_click: true
  use_percentage_bg_opacity: true
  show_track: true
  force_square: false
icon:
  icon: ''
  tap_action:
    action: none
  show: true
  use_state_color: true
show_attribute: false
show_name: true
compact: false
action_button:
  mode: custom
  show: true
  show_spinner: true
  tap_action:
    action: call-service
    service: switch.toggle
    target:
      entity_id: switch.boiler_controler_boiler_overide_switch
    data: {}

# End of code
```

**Additional information:**
