### ISSUE TITLE
Text is cut off on mobile

### ISSUE THREAD

**Issue by marcuscps** [custom-cards/slider-button-card#79]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.13.0

**Last working release (if known):**

**Browser and Operating System:**
Android Pixel 7

**Description of problem:**

The Text is getting cut off on mobile (vertically). Characters like g (that extend below the text baseline) at getting chopped off.

**Javascript errors shown in the web inspector (if applicable):**
None

**Additional information:**

I can reproduce it this way:
```
type: custom:slider-button-card
entity: climate.living_room
name: Living Room
compact: true
show_name: true
show_state: true
show_attribute: true
attribute: current_temperature
slider:
  background: gradient
  show_track: true
  toggle_on_click: false
  show_attribute: false
  direction: left-right
  use_percentage_bg_opacity: true
  use_state_color: true
  force_square: false
icon:
  show: true
  icon: mdi:heating-coil
  use_state_color: true
  tap_action:
    action: more-info
action_button:
  show: false
```

Looks like this:
![Screenshot_20240829-181058](https://github.com/user-attachments/assets/9e30d41a-4a62-4e85-8ac5-078eb1d7f3d7)

And when slidding:
![Screenshot_20240829-181123](https://github.com/user-attachments/assets/891bdca9-0bd0-4d75-9615-5b432efd9d6c)
