### ISSUE TITLE
Sider level change affects other switched On devices' slider level

### ISSUE THREAD

**Issue by jimkhoo** [custom-cards/slider-button-card#84]
**Checklist:**

- [ X ] I updated to the latest version available
- [ X ] I cleared the cache of my browser
- [ X ] I rebooted my home assistant
- [ X ] I tested on different devices and browsers

**Release with the issue:** v1.13.0

**Last working release (if known):** N/A v1.13 is first install

**Browser and Operating System:**

Google Chrome v131.0.6778.265 / Windows 11 64 bit
Microsoft Edge v131.0.2849.142 / Windows 11 64 bit
Home Assistant App 2025.1.2-full / Android 12

Home Assistant Details
Core: 2025.1.2
Supervisor: 2025.12.3
Operating System: 14.1
Frontend: 20250109.0

**Description of problem:**

When charging level on one of the slider, all other sliders that are in On state will change their level to match the changed level. Toggling on or off does not affect others.

Steps to reproduce issue as follows:

Step 1. Create multiple slider cards with following settings.

type: custom:slider-button-card
entity: <entity>
slider:
  direction: left-right
  background: gradient
  use_state_color: true
  use_percentage_bg_opacity: true
  show_track: false
  toggle_on_click: false
  force_square: false
  show_attribute: false
show_name: true
show_state: true
compact: true
icon:
  show: true
  use_state_color: true
  tap_action:
    action: more-info
  icon: ""
action_button:
  mode: toggle
  icon: mdi:power
  show: true
  show_spinner: true
  tap_action:
    action: toggle
name: <friendly name>

Step 2: Switch on all slider card entities
Step 3: Change slider level on any of the entity
Step 4: Observe level change on all slider cards to match last changed level.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by jimkhoo** [comment]
![Screenshot_20250114_101824](https://github.com/user-attachments/assets/f4d93bf9-9be0-4158-a95c-e9d28c78c04a)

**Comment by rohankapoorcom** [comment]
Hi @jimkhoo can you provide some more details (including the full config of each of those sliders with entities)? Please include the config inside a code block (with 3 backticks ``` enclosing it)

I'm unable to reproduce with the example provided so far. I have pages on my dashboard with 20+ sliders and all of them are maintaining their independence.

**Comment by jimkhoo** [comment]
Hi @rohankapoorcom,

Thanks for reaching out. Please see below for the complete raw config for the dashboard containing the 3 sliders. Let me know if you need anything. Thanks.

```
views:
  - title: Home
    sections: []
    type: masonry
    cards:
      - type: custom:slider-button-card
        entity: light.dininglightdimmer_dininglightdimmer
        slider:
          direction: left-right
          background: gradient
          use_state_color: true
          use_percentage_bg_opacity: true
          show_track: true
          toggle_on_click: false
          force_square: false
          show_attribute: false
        show_name: true
        show_state: true
        compact: true
        icon:
          show: true
          use_state_color: true
          tap_action:
            action: more-info
          icon: ''
        action_button:
          mode: toggle
          icon: mdi:power
          show: true
          show_spinner: true
          tap_action:
            action: toggle
        name: Dining Dimmer
      - type: custom:slider-button-card
        entity: light.officelightdimmer_officelightdimmer
        slider:
          direction: left-right
          background: gradient
          use_state_color: true
          use_percentage_bg_opacity: true
          show_track: true
          toggle_on_click: false
          force_square: false
          show_attribute: false
        show_name: true
        show_state: true
        compact: true
        icon:
          show: true
          use_state_color: true
          tap_action:
            action: more-info
          icon: ''
        action_button:
          mode: toggle
          icon: mdi:power
          show: true
          show_spinner: true
          tap_action:
            action: toggle
        name: Office Dimmer
      - type: custom:slider-button-card
        entity: light.masterroomdimmer_masterroomdimmer
        slider:
          direction: left-right
          background: gradient
          use_state_color: true
          use_percentage_bg_opacity: true
          show_track: true
          toggle_on_click: false
          force_square: false
          show_attribute: false
        show_name: true
        show_state: true
        compact: true
        icon:
          show: true
          use_state_color: true
          tap_action:
            action: more-info
          icon: ''
        action_button:
          mode: toggle
          icon: mdi:power
          show: true
          show_spinner: true
          tap_action:
            action: toggle
        name: Master Room Dimmer
```
