### ISSUE TITLE
Not working - invalid configuration / installed directly from HACS

### ISSUE THREAD

**Issue by oskarroza** [custom-cards/slider-button-card#85]
The card is not working. HA detects invalid configuartion and fails to load the card.

```
Invalid configuration
type: custom:slider-button-card
entity: ''
slider:
  direction: left-right
  background: gradient
  use_state_color: true
  use_percentage_bg_opacity: false
  show_track: false
  toggle_on_click: false
  force_square: false
  show_attribute: false
show_name: true
show_state: true
compact: false
icon:
  show: true
  use_state_color: true
  tap_action:
    action: more-info
action_button:
  mode: toggle
  icon: mdi:power
  show: true
  show_spinner: true
  tap_action:
    action: toggle
```

HA: 2025.2.4
Device: RPI 4
