### ISSUE TITLE
tap-action : more-info + entity key and consistency with home assistant tap_action documentation

### ISSUE THREAD

**Issue by ndesgranges** [custom-cards/slider-button-card#86]
**Is your feature request related to a problem? Please describe.**

Home assistant [tap-action documentation](https://www.home-assistant.io/dashboards/actions/#tap-action) states the key `entity` can be used with `more-info`actions to set the more-info target.

This does not seem to be supported in slider-button-card.

**Describe the solution you'd like**

Use key `entity` to change what entity the more-info popup shows

**Additional context**

Example: Snapcast entity

> _Snapcast is an audio server used to send audio to many devices (speakers) to play together the same audio at the same time. It is very useful to synchronise music between multiple speakers._

using snapcast integration, I can set the volume of a speaker (snapcast entity). The more-info doesn't show any useful information other than the volume already shown on the slider.

I would like to be able to show and change the latency of a speaker from the more-info when I click the icon

> _Snapcast features an action to set the latency, but there is no related number entity. I set up an `input_number` entity with an automation to use the set latency action when my created `input-number` changes_

example yaml (simplified for the sake of the issue) :

```yaml
type: custom:slider-button-card
entity: media_player.speaker_1_snapcast_client
slider:
  direction: left-right
  show_name: true
  show_state: true
  icon:
    show: true
    use_state_color: false
    tap_action:
      action: more-info
      entity: input_number.speaker_1_snapcast_LATENCY_SETTER
      icon: mdi:any-icon
  name: Speaker 1
  attribute: volume_level
  show_attribute: false
```
